substitutions:
  name: darkbeam
  friendly_name: Darkbeam

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: dev

esp32:
  board: esp32-s3-devkitc-1
  variant: ESP32S3
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  ssid: "YOUR_SSID"
  password: "YOUR_PASSWORD"

  # Enable fallback hotspot in case of Wi-Fi issues
  ap:
    ssid: "Darkbeam Fallback Hotspot"
    password: "d4rkb34m!"

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

dashboard_import:
  package_import_url: github://esphome/example-configs/esphome-web/esp32.yaml@main
  import_full_config: true

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
esp32_improv:
  authorizer: none

# To have a "next url" for improv serial
web_server:

# ====================

i2c:
  sda: GPIO39  # Adjust GPIO pins if using AtomS3 Lite
  scl: GPIO38
  scan: true

time:
  - platform: sntp
    id: sntp_time

# Use ESPHome's built-in Roboto fonts
font:
  - file: "gfonts://Roboto"
    id: small_font
    size: 22  # Small font for date (Roboto built-in)
  - file: "gfonts://Roboto"
    id: large_font
    size: 44  # Large font for time (Roboto built-in)

light:
  - platform: neopixelbus
    name: "Darkbeam LED"
    type: GRB
    variant: SK6812
    pin: GPIO35
    num_leds: 1
    

binary_sensor:
  - platform: gpio
    name: "Darkbeam Button"
    pin:
      number: GPIO41
      inverted: true
      mode:
        input: true
    filters:
      - delayed_on: 10ms

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    flip_x: true
    flip_y: false
    lambda: |-
      // Display date with weekday, day, and month in small font at the top
      it.strftime(0, 0, id(small_font), "%a, %d.%m.", id(sntp_time).now());

      // Display time (HH:MM) in large font below
      it.strftime(0, 22, id(large_font), "%H:%M", id(sntp_time).now());
